name: Twall
packages:
  TwallCore:
    path: .
targets:
  twall-app:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources: App
    dependencies:
      - package: TwallCore
        product: TwallCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ttickell.twall
        INFOPLIST_FILE: App/Info.plist
        SWIFT_VERSION: 5.9
